name: test-pippin
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "docs/**"
      - ".github/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".github/**"
    workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Python ${{ matrix.python-version }} - ${{ github.event_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        # '3.7' is the minimum supported version
        # '3.x' is the lateest minor release of Python 3
        python-version: ["3.7.x", "3.x"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install -U numpy

      - name: Setup pippin
        run: |
          python setup.py sdist

      - name: Test pippin
        run: |
          pytest -v .
        env:
          SNANA_DIR: SNANA_DIR
